theme = "Lanyon"
baseURL = "https://bohan.co/"
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true
pygmentsUseClasses = true

[permalinks]
posts = "/:filename/"

[params]
description = "Modern PHP Developer | Debian VPS Player | Docker Image Maintainer | DNS & SSL/TLS & CDN Enthusiast"

titleSeparator = " - "

[languages]

[languages.zh-hans]

languageName = "中文（简体）"
title = "Bohan Yang"
tagline = "a.k.a. Brent"

[languages.zh-hans.menu]

[[languages.zh-hans.menu.main]]
name = "English"
url  = "/en/"
weight = 4

[languages.en]

languageName = "English"
title = "Bohan Yang"
tagline = "a.k.a. Brent"

[languages.en.menu]

[[languages.en.menu.main]]
name = "中文（简体）"
url  = "/"
weight = 4
