theme = "Lanyon"
baseURL = "https://bohan.co/"
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true
pygmentsUseClasses = true

[permalinks]
posts = "/:year/:month/:day/:filename/"

[params]
description = "Modern PHP Developer | Debian VPS Player | Docker Image Maintainer | DNS & SSL/TLS & CDN Enthusiast"

titleSeparator = " - "

[languages]

[languages.zh-hans]

languageName = "中文（简体）"
useLanguageCode = "zh-Hans"
title = "晨清露澄"
tagline = "一些有用没用的东西"
icpLicense = "粤ICP备19081223号"

[languages.zh-hans.menu]

[[languages.zh-hans.menu.main]]
name = "English"
url  = "/en/"
weight = 4

[languages.en]

languageName = "English"
title = "Freespace"
tagline = "by Bohan Yang"

[languages.en.menu]

[[languages.en.menu.main]]
name = "中文（简体）"
url  = "/"
weight = 4
