[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"

[[redirects]]
from = "/archives/*"
to = "/:splat"
status = 301
