[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"

[[redirects]]
from = "/archives/*"
to = "/:splat"
status = 301

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "max-age=604800"
